// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4vlbneqHc3o3ZyygSmUSnPVyQ5w92YSs',
    appId: '1:416757773652:web:075a86f02709c5023d04c1',
    messagingSenderId: '416757773652',
    projectId: 'flutter-chat-app-e83ed',
    authDomain: 'flutter-chat-app-e83ed.firebaseapp.com',
    storageBucket: 'flutter-chat-app-e83ed.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8oT0yzQ9StgKx1AnlEt5djvjHTWLoGoY',
    appId: '1:416757773652:android:c715f7b88f234ee43d04c1',
    messagingSenderId: '416757773652',
    projectId: 'flutter-chat-app-e83ed',
    storageBucket: 'flutter-chat-app-e83ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_o6K_V5_XPM4Hloe66g1uRSnYC5qEZdo',
    appId: '1:416757773652:ios:5d979fee71d2317f3d04c1',
    messagingSenderId: '416757773652',
    projectId: 'flutter-chat-app-e83ed',
    storageBucket: 'flutter-chat-app-e83ed.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_o6K_V5_XPM4Hloe66g1uRSnYC5qEZdo',
    appId: '1:416757773652:ios:c1660b9f3b6279f53d04c1',
    messagingSenderId: '416757773652',
    projectId: 'flutter-chat-app-e83ed',
    storageBucket: 'flutter-chat-app-e83ed.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
